### ISSUE TITLE
Cannot install TurnVoice on Fedora 40 python virtual env 3.11

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [KoljaB/TurnVoice#11]
I get a strange error:
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [167 lines of output]

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          int length

      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
                ^
      ------------------------------------------------------------

      spacy/vocab.pxd:28:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead                                                                                                                                                   .

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
                ^
      ------------------------------------------------------------

      spacy/vocab.pxd:29:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead                                                                                                                                                   .

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
                ^
      ------------------------------------------------------------

      spacy/vocab.pxd:30:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead                                                                                                                                                   .

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
                ^
      ------------------------------------------------------------

      spacy/vocab.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead                                                                                                                                                   .

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
                ^
      ------------------------------------------------------------

      spacy/vocab.pxd:32:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead                                                                                                                                                   .

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
          cpdef public object get_noun_chunks
                ^
      ------------------------------------------------------------

      spacy/vocab.pxd:33:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead                                                                                                                                                   .

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef float prior_prob

      cdef class KnowledgeBase:
          cdef Pool mem
          cpdef readonly Vocab vocab
                ^
      ------------------------------------------------------------

      spacy/kb.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      Copied /tmp/pip-install-5ey84xom/spacy_84c15929ea934158aab0bd0c00f9023c/setup.cfg ->                                                                                                                                                    /tmp/pip-install-5ey84xom/spacy_84c15929ea934158aab0bd0c00f9023c/spacy/tests/package
      Copied /tmp/pip-install-5ey84xom/spacy_84c15929ea934158aab0bd0c00f9023c/pyproject.to                                                                                                                                                   ml -> /tmp/pip-install-5ey84xom/spacy_84c15929ea934158aab0bd0c00f9023c/spacy/tests/package
      Cythonizing sources
      Compiling spacy/training/example.pyx because it changed.
      Compiling spacy/parts_of_speech.pyx because it changed.
      Compiling spacy/strings.pyx because it changed.
      Compiling spacy/lexeme.pyx because it changed.
      Compiling spacy/vocab.pyx because it changed.
      Compiling spacy/attrs.pyx because it changed.
      Compiling spacy/kb.pyx because it changed.
      Compiling spacy/ml/parser_model.pyx because it changed.
      Compiling spacy/morphology.pyx because it changed.
      Compiling spacy/pipeline/dep_parser.pyx because it changed.
      Compiling spacy/pipeline/morphologizer.pyx because it changed.
      Compiling spacy/pipeline/multitask.pyx because it changed.
      Compiling spacy/pipeline/ner.pyx because it changed.
      Compiling spacy/pipeline/pipe.pyx because it changed.
      Compiling spacy/pipeline/trainable_pipe.pyx because it changed.
      Compiling spacy/pipeline/sentencizer.pyx because it changed.
      Compiling spacy/pipeline/senter.pyx because it changed.
      Compiling spacy/pipeline/tagger.pyx because it changed.
      Compiling spacy/pipeline/transition_parser.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/arc_eager.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/ner.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/nonproj.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_state.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/stateclass.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/transition_system.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_beam_utils.pyx because it changed.
      Compiling spacy/tokenizer.pyx because it changed.
      Compiling spacy/training/align.pyx because it changed.
      Compiling spacy/training/gold_io.pyx because it changed.
      Compiling spacy/tokens/doc.pyx because it changed.
      Compiling spacy/tokens/span.pyx because it changed.
      Compiling spacy/tokens/token.pyx because it changed.
      Compiling spacy/tokens/span_group.pyx because it changed.
      Compiling spacy/tokens/graph.pyx because it changed.
      Compiling spacy/tokens/morphanalysis.pyx because it changed.
      Compiling spacy/tokens/_retokenize.pyx because it changed.
      Compiling spacy/matcher/matcher.pyx because it changed.
      Compiling spacy/matcher/phrasematcher.pyx because it changed.
      Compiling spacy/matcher/dependencymatcher.pyx because it changed.
      Compiling spacy/symbols.pyx because it changed.
      Compiling spacy/vectors.pyx because it changed.
      [ 1/41] Cythonizing spacy/attrs.pyx
      [ 2/41] Cythonizing spacy/kb.pyx
      Traceback (most recent call last):
        File "/home/httpd/html/WebSites/e-blokos.com/VIDEOPROC/env_turnvoice/lib64/python3                                                                                                                                                   .11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <m                                                                                                                                                   odule>
          main()
        File "/home/httpd/html/WebSites/e-blokos.com/VIDEOPROC/env_turnvoice/lib64/python3                                                                                                                                                   .11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in ma                                                                                                                                                   in
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/httpd/html/WebSites/e-blokos.com/VIDEOPROC/env_turnvoice/lib64/python3                                                                                                                                                   .11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in ge                                                                                                                                                   t_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-irclfo0x/overlay/lib/python3.11/site-packages/setuptools/                                                                                                                                                   build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-irclfo0x/overlay/lib/python3.11/site-packages/setuptools/                                                                                                                                                   build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-irclfo0x/overlay/lib/python3.11/site-packages/setuptools/                                                                                                                                                   build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "/tmp/pip-build-env-irclfo0x/overlay/lib64/python3.11/site-packages/Cython/Bu                                                                                                                                                   ild/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-irclfo0x/overlay/lib64/python3.11/site-packages/Cython/Bu                                                                                                                                                   ild/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

any idea?

**Comment by KoljaB** [comment]
Might need to upgrade Cython but that's really only an idea. I developed this for Windows and since it's a complex project I wouldn't expect it to work out of the box under a linux platform.

**Comment by ROBERT-MCDOWELL** [comment]
arggh :(((. what version of spacy TurnVoice needs?

**Comment by KoljaB** [comment]
Prob related to:
https://github.com/idiap/coqui-ai-TTS/pull/92#pullrequestreview-2347635179
Might need to use latest RealtimeTTS version.

**Comment by ROBERT-MCDOWELL** [comment]
Ok do you mean that Imust install realltimetts and turnvoice?

**Comment by ROBERT-MCDOWELL** [comment]
Good news, I succeeded to instal TurnVoice on Fedora 40 with python virtual env 3.11.
I forced to install 
pip install spacy==3.7.5, then simple pip install cython, pip install turnvoice.

**Comment by KoljaB** [comment]
I think that should work.

**Comment by ROBERT-MCDOWELL** [comment]
I will check which package version can be upgraded so I will PR.

**Comment by ROBERT-MCDOWELL** [comment]
Ok for now I'm stuck with the test scripts. is there any option to test with CPU only?

**Comment by kazishariar** [comment]
Can this be used on apple silicone without CUDA, but apple m1 has multiple fast gpus

EDIT: Sorry, reason I came here is kudos Bob, on getting Windowsmade dev to Fedora Core, hoping to see you with the hat on, adding ulling requests with updates. I'll make one with Mac as well ;-) TY!

P.S. K.B you are t3h awesome! Stay awesome-
